FROM openknowledge/ckan-dev:2.8

MAINTAINER Open Knowledge International <info@okfn.org>

# Install utilities
RUN pip install ipdb ipdbplugin

# Install any extensions needed by your CKAN instance
# (Make sure to add the plugins to CKAN__PLUGINS in the .env file)
# TODO: pin when possible
RUN echo 'Installing extensions' && \
    # googleanalytics
    pip install -e git+https://github.com/ckan/ckanext-googleanalytics.git#egg=ckanext-googleanalytics && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-googleanalytics/master/requirements.txt && \
    # pages
    pip install -e git+https://github.com/ckan/ckanext-pages.git#egg=ckanext-pages && \
    # geoview
    pip install -e git+https://github.com/roll/ckanext-geoview.git@#egg=ckanext-geoview && \
    # pdfview
    pip install -e git+https://github.com/ckan/ckanext-pdfview.git#egg=ckanext-pdfview && \
    # scheming
    pip install -e git+https://github.com/ckan/ckanext-scheming.git#egg=ckanext-scheming && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-scheming/master/requirements.txt && \
    # harvest
    pip install -e git+https://github.com/ckan/ckanext-harvest.git#egg=ckanext-harvest && \
    pip install -r https://raw.githubusercontent.com/ckan/ckanext-harvest/master/pip-requirements.txt && \
    # disqus
    pip install -e git+https://github.com/okfn/ckanext-disqus#egg=ckanext-disqus
